// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYF_m4iFeSLK1OQbC-hSeo253CKzu-Otc',
    appId: '1:159157977140:web:fb2f463810ec120eef4a61',
    messagingSenderId: '159157977140',
    projectId: 'music-groups-9b0cb',
    authDomain: 'music-groups-9b0cb.firebaseapp.com',
    databaseURL: 'https://music-groups-9b0cb.firebaseio.com',
    storageBucket: 'music-groups-9b0cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZKG6vERrsv8fjP6cERf1_tdQ5Xx36ig',
    appId: '1:159157977140:android:e623b20938964ec4ef4a61',
    messagingSenderId: '159157977140',
    projectId: 'music-groups-9b0cb',
    databaseURL: 'https://music-groups-9b0cb.firebaseio.com',
    storageBucket: 'music-groups-9b0cb.appspot.com',
  );
}
